---
title: "Codes for calculation of climate data"
pagetitle: "Supplementary code for data calculation"
author: 
- <a href="https://gitee.com/auman-chan"> Auman Chan, PhD Candidate</a>
date:  "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    df_print: kable
    self_contained: yes
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
vignette: >
  %\VignetteIndexEntry{2. Supplementary code for data calculation}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
  
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  
  chunk_output_type: console
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
---
```{css,echo=FALSE}

body {
  margin-top: 16px;
  margin-bottom: 16px;
  font-size: 19px;
  font-weight: 200;
}

#sidebar {
font-size: 16px
}

#sidebar p {
font-size: 16px
}

.contents h1, .contents h2, .contents h3, .contents h4 {
  padding-top: 60px;
  margin-top: -50px;
}

h4 {
  font-size: 19px;
}

h3 {
  font-size: 22px;
}

h2 {
  font-size: 26px;
}

h1 {
  font-size: 30px;
}

pre {
  border: 0;
  overflow-x: auto;
  white-space: pre-wrap;
  white-space: -moz-pre-wrap;
  white-space: -pre-wrap;
  white-space: -o-pre-wrap;
  word-wrap: break-word;
  background: #e9f7ed;
    color: #ffffff;
    padding-top: 0.5em;
  padding-bottom: 0.5em;
  padding-left: 20px;
  padding-right: 20px;
  line-height: 21px;
  font-size: 15px;
}

pre code {
  color: #182125;
}

code {
  word-wrap: break-word;
  font-size: 85%;
  font-family: Consolas,Monaco,"Courier New",monospace;
  border-radius: 0;
}

.nav-pills>li>a {
  border-radius: 0;
}

.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover {
  color: #408AB4;
}
.navbar-default .navbar-nav>li>a {
  color: #408AB4;
}

table p {
  font-size: 85%;
}

.ref-index h2 {
  font-size: 24px;
}

h1.title {
  font-weight: bold;
  font-size: 180%;
  text-align: center
}

h2.subtitle {
  font-size: 120%;
  text-align: center
}

h3.subtitle {
  font-size: 120%;
  text-align: center
}

h4.author {
  font-size: 120%;
  text-align: center
}

h4.date {
  font-size: 120%;
  text-align: center
}

p {
  margin-bottom: 30px;
}
```


If you wish to perform the dataset calculations independently, please download the original data and refer to the code provided below. Due to high memory usage and time requirements, we have refrained from incorporating these codes as a package function.

The download link of original data as below:

[2010-2019 monthly minimum temperature](https://geodata.ucdavis.edu/climate/worldclim/2_1/hist/cts4.06/2.5m/wc2.1_cruts4.06_2.5m_tmin_2010-2019.zip)

[2010-2019 monthly maximum temperature](https://geodata.ucdavis.edu/climate/worldclim/2_1/hist/cts4.06/2.5m/wc2.1_cruts4.06_2.5m_tmax_2010-2019.zip)

[2010-2019 monthly precipitation](https://geodata.ucdavis.edu/climate/worldclim/2_1/hist/cts4.06/2.5m/wc2.1_cruts4.06_2.5m_prec_2010-2019.zip)

The code for cacluation are as below:

- **imp_path**: path of import Worldclim Historical monthly weather data,
every kind of dataset(mintemp,maxtemp,prec)should be saparated in different folders

- **exp_path**: path of export arranged data in format of .tif

- **name**: the name of .tif file to differentiate the data

- **method**: the method for calculating the raster,default is "mean" to calculate
annual average climatic values. 
Set as "min" to calculate annual minimum climatic values for forsty month display.

```{r  cal_code,eval=FALSE}
library(raster)
library(dplyr)
library(stringr)
library(future.apply)
library(parallel)

clim_cal <- function(imp_path,
                     exp_path,
                     name=NA,
                     method="mean",
                     parallel=1,
                     ...){
tifname <- list.files(imp_path,full.names = T)

rastermean <- function(num){
  tif <- tifname[tifname %>% str_detect(pattern = paste0("-",num,".tif"))]
  val <- lapply(tif,raster) %>% raster::brick() %>% calc(mean)
  return(val)
}

rastermin <- function(num){
  tif <- tifname[tifname %>% str_detect(pattern = paste0("-",num,".tif"))]
  val <- lapply(tif,raster) %>% brick() %>% calc(min)
  return(val)
}

plan(multisession,workers= parallel)
month <- c(1:12) %>% str_pad(2,side = "left","0")

if(method=="mean"){
  raster <- future_lapply(month,function(x) rastermean(x))
}else if(method=="min"){
  raster <- future_lapply(month,function(x) rastermin(x))
}

rasterstack <- raster %>% stack()
path <- exp_path
for(i in 1:12){
  ras <- raster(rasterstack,layer=i)
  #export the RasterLayer
  writeRaster(ras,file.path(path,paste0(name,"_",month[i],".tif")))
}

}

```

## Reference
1. Fick, S.E. and R.J. Hijmans, (2017). WorldClim 2: new 1km spatial resolution climate surfaces for global land areas. International Journal of Climatology 37 (12): 4302-4315.

2.  Harris, I., Osborn, T.J., Jones, P.D., Lister, D.H. (2020). Version 4 of the CRU TS monthly high-resolution gridded multivariate climate dataset. Scientific Data 7: 109.


